### ISSUE TITLE
Linters list

### ISSUE THREAD

**Issue by soullivaneuh** [Soullivaneuh/composer-lint#1]
## Linters to be written before stable version
- [x] Sort packages #2
- [x] PHP requirement #3
- [x] Prevent minimum-stability (if type specified and not a project) #4
- [x] Required package `type` #5
- [x] Constraint format (e.g. `^` instead of `~`, `||` instead of `|`...) #6
- [x] Documentation about options on readme file

**Comment by greg0ire** [comment]
Prevent "minimum-stability" ?

**Comment by soullivaneuh** [comment]
> Prevent "minimum-stability" ?

I was thinking about that but when the error should be thrown?

`mininum-stability` has many option (`dev`, `alpha`...) and work also with `prefer-stable` one.

And should be activate this linter by default? I agree that this option is not recommended for a library but looks correct for a private project.

**Comment by greg0ire** [comment]
> I agree that this option is not recommended for a library but looks correct for a private project.

You can detect if a Composer package is a library or project, it's written in the JSON manifest.

**Comment by soullivaneuh** [comment]
> You can detect if a Composer package is a library or project, it's written in the JSON manifest.

Yeah. But I think this is an option that should be `false` by default.

`mininum-stability` is more a matter of taste on usage than a composer CS IMHO.

**Comment by soullivaneuh** [comment]
Finished! :tada: 

Thanks @greg0ire for your help and support! :smile:
